=== SanekP/SeriesInformer/UI/src/main/resources/db/dbschema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://seriesinformer.sanekp"
           xmlns="http://seriesinformer.sanekp" elementFormDefault="qualified">
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="series" type="seriesType" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="seriesType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="season" type="xs:integer"/>
            <xs:element name="episode" type="xs:integer"/>
            <xs:element name="url" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== SanekP/SeriesInformer/Core/src/main/resources/db/db.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://seriesinformer.sanekp"
      xsi:schemaLocation="http://seriesinformer.sanekp dbschema.xsd">
    <series>
        <name>Game of Thrones</name>
        <season>5</season>
        <episode>10</episode>
        <url>http://brb.to/video/serials/ifdtLsEYPLkQmOfjEkZFfO-igra-prestolov.html</url>
    </series>
    <series>
        <name>The Walking Dead</name>
        <season>6</season>
        <episode>8</episode>
        <url>http://brb.to/video/serials/i13P2ZgWBj7wrR4IdAS1O0-hodyachije-mertvecy.html</url>
    </series>
    <series>
        <name>The Big Bang Theory</name>
        <season>8</season>
        <episode>24</episode>
        <url>http://fs.to/video/serials/i5nZGw8N0guCAuCqwvgB0gE-teoriya-bolshogo-vzryva.html</url>
    </series>
    <series>
        <name>Agents of S.H.I.E.L.D</name>
        <season>3</season>
        <episode>10</episode>
        <url>http://fs.to/video/serials/iLeIMlRZKskGzLvIiI8joA-agenty-shh-i-t.html</url>
    </series>
    <series>
        <name>Person of Interest</name>
        <season>1</season>
        <episode>16</episode>
        <url>http://brb.to/video/serials/igdp23OQOkZsRC56XQFVeM-v-pole-zreniya.html</url>
    </series>
    <series>
        <name>Under the Dome</name>
        <season>3</season>
        <episode>13</episode>
        <url>http://brb.to/video/serials/ifdtHOAyPyMxTp0jaHePew-pod-kupolom.html</url>
    </series>
    <series>
        <name>Mr. Robot</name>
        <season>1</season>
        <episode>10</episode>
        <url>http://fs.to/video/serials/iw58NuFBdGjSnp76oTETVC-mister-robot.html</url>
    </series>
    <series>
        <name>Fear the Walking Dead</name>
        <season>1</season>
        <episode>0</episode>
        <url>http://fs.to/video/serials/i4pC9U7QEMTgMsznH9hFrI4-bojtes-khodyachih-mertvecov.html</url>
    </series>
    <series>
        <name>Castle</name>
        <season>7</season>
        <episode>22</episode>
        <url>http://fs.to/video/serials/i4ELvFbodP7u3YGBACYSPqo-kasl.html</url>
    </series>
    <series>
        <name>House of Cards</name>
        <season>1</season>
        <episode>0</episode>
        <url>http://fs.to/video/serials/iMaZnsM0Bu9XUrykJcMbG8-kartochnyj-domik.html</url>
    </series>
    <series>
        <name>Bron/Broen</name>
        <season>2</season>
        <episode>9</episode>
        <url>http://fs.to/video/serials/i4ELwBvNFeedUEtukY7KUaQ-most.html</url>
    </series>
    <series>
        <name>Fargo</name>
        <season>2</season>
        <episode>10</episode>
        <url>http://fs.to/video/serials/iMb0cUQyusQCvXDNKahvLa-fargo.html</url>
    </series>
</list>
